// Original research notes; full provenance and rights review: docs/cyber/SOURCES.md.
const retrievedAt = '2026-09-24';
const source = (id, publisher, title, url, publishedAt, locator, summary) => ({
  id,
  publisher,
  title,
  url,
  publishedAt,
  retrievedAt,
  locator,
  summary,
  access: 'Public HTML; manually reviewed',
  rights:
    'Copyright retained by source. Original paraphrase and link; no open redistribution license established.',
  transformation:
    'Concise English research note; dates normalized without inventing time precision.',
});

/** Curated source records are isolated from the canonical UI model. */
export const sourceNotes = [
  source(
    'src-kyivstar',
    'Kyivstar',
    'Service recovery after the cyberattack',
    'https://kyivstar.ua/news/id191220231000',
    '2023-12-19',
    'Why Kyivstar did not work; personal data; service availability sections',
    'Kyivstar says the 12 December attack interrupted mobile and Internet services. It says subscriber personal data was not compromised. Recovery work continued.',
  ),
  source(
    'src-cloudflare',
    'Cloudflare Radar · David Belson',
    'Q4 2023 Internet disruption summary',
    'https://blog.cloudflare.com/q4-2023-internet-disruption-summary/',
    '2024-01-22',
    'Cyberattacks → Ukraine; linked Kyivstar AS15895 chart',
    'Cloudflare describes a Kyivstar traffic disruption from 12 December 04:30 UTC to 15 December 12:00 UTC. This is its network vantage point, not a census of subscribers.',
  ),
  source(
    'src-voice',
    'VEON / Kyivstar',
    'Voice service restoration begins',
    'https://www.globenewswire.com/news-release/2023/12/13/2795840/0/en/Kyivstar-starts-restoring-voice-services-on-its-network-following-widespread-cyber-attack.html',
    '2023-12-13',
    'Opening two paragraphs',
    'VEON reports mobile voice restoration beginning at 18:00 Kyiv time on 13 December. Restoration is gradual, with possible setbacks.',
  ),
  source(
    'src-mobile',
    'VEON / Kyivstar',
    'Mobile Internet restored across Ukraine',
    'https://www.globenewswire.com/news-release/2023/12/15/2797248/0/en/Kyivstar-restores-mobile-internet-across-Ukraine-reactivates-international-roaming.html',
    '2023-12-15',
    'Opening paragraphs and customer experience qualification',
    'VEON reports mobile Internet restored across Ukraine, including 4G, while warning that individual experience and service quality may vary.',
  ),
  source(
    'src-recovery',
    'VEON / Kyivstar',
    'Service categories restored; 99% of base stations operational',
    'https://www.globenewswire.com/news-release/2023/12/19/2798765/0/en/Kyivstar-restores-services-in-all-categories-brings-99-of-mobile-network-back-on-air.html',
    '2023-12-19',
    'Opening three paragraphs',
    'VEON reports all service categories available and 99% of base stations operational in Ukrainian-government-controlled territory. Quality and accessibility work continued.',
  ),
  {
    ...source(
      'src-geography',
      'Natural Earth',
      'Admin 0 countries · 1:110m · v5.1.2',
      'https://github.com/nvkelso/natural-earth-vector/blob/v5.1.2/geojson/ne_110m_admin_0_countries.geojson',
      null,
      'Feature ADM0_A3 = UKR',
      'Generalized country outline; reference geography only. It does not describe territorial control or outage extent.',
    ),
    rights: 'Public domain. Courtesy credit: Natural Earth.',
    transformation:
      'Select UKR feature; retain geometry only in canonical bundle.',
  },
];

/** Adapt reviewed static notes and reference geometry into canonical objects. */
export function normalizeKyivstar(ukraine) {
  const evidence = sourceNotes.map((s) => ({
    id: s.id.replace('src-', 'ev-'),
    provenanceId: s.id,
    locator: s.locator,
    summary: s.summary,
  }));
  const time = (id, start, end, precision = 'day', basis = 'EVENT_TIME') => ({
    id,
    start,
    end,
    precision,
    basis,
  });
  const claim = (
    id,
    text,
    status,
    subjects,
    evidenceIds,
    timeId,
    limitation,
    extra = {},
  ) => ({
    id,
    text,
    status,
    subjects,
    evidenceIds,
    timeId,
    limitation,
    ...extra,
  });
  return {
    schemaVersion: 1,
    id: 'kyivstar-2023',
    title: 'Kyivstar',
    subtitle: 'Cyberattack & telecommunications outage',
    provenance: sourceNotes,
    evidence,
    times: [
      time('t-attack', '2023-12-12', '2023-12-12'),
      time(
        't-disruption',
        '2023-12-12T04:30:00Z',
        '2023-12-15T12:00:00Z',
        'minute',
      ),
      time('t-voice', '2023-12-13T16:00:00Z', '2023-12-13T16:00:00Z', 'minute'),
      time('t-mobile', '2023-12-15', '2023-12-15'),
      time('t-recovery', '2023-12-19', '2023-12-19'),
      time('t-reference', retrievedAt, retrievedAt, 'day', 'CURRENT_REFERENCE'),
    ],
    entities: [
      {
        id: 'kyivstar',
        type: 'organization',
        name: 'Kyivstar',
        description:
          'Telecommunications operator. Organization-level subject; no inferred headquarters or attack coordinate.',
      },
      {
        id: 'as15895',
        type: 'network',
        name: 'AS15895',
        description:
          'Network identified by the Cloudflare report’s Kyivstar link. An autonomous system is a logical network, not a point on Earth.',
      },
      {
        id: 'ukraine',
        type: 'country',
        name: 'Ukraine',
        description:
          'Country-level context. The outline does not imply uniform outage, network coverage or territorial control.',
      },
    ],
    geometries: [
      {
        id: 'geo-ukraine',
        type: ukraine.type,
        coordinates: ukraine.coordinates,
        crs: 'EPSG:4326',
        timeId: 't-reference',
        evidenceIds: ['ev-geography'],
        role: 'REFERENCE_CONTEXT',
      },
    ],
    observations: [
      {
        id: 'obs-traffic',
        subjectId: 'as15895',
        observer: 'Cloudflare Radar',
        metric: 'Internet traffic disruption interval',
        method: 'published-summary',
        value: null,
        unit: null,
        timeId: 't-disruption',
        evidenceIds: ['ev-cloudflare'],
        limitation:
          'Published measurement summary; no raw samples, percentage drop, or per-location measurements imported.',
      },
    ],
    claims: [
      claim(
        'c-attack',
        'Kyivstar reports a cyberattack interrupting mobile and Internet services on 12 December.',
        'REPORTED',
        ['kyivstar'],
        ['ev-kyivstar'],
        't-attack',
        'Operator account. This bundle does not independently establish the attack mechanism.',
      ),
      claim(
        'c-traffic',
        'Cloudflare measured a disruption in Kyivstar Internet traffic spanning 12–15 December.',
        'OBSERVED',
        ['as15895'],
        ['ev-cloudflare'],
        't-disruption',
        'Observed by Cloudflare, retained as a published summary. Internet traffic is not a direct measurement of voice service.',
        { observationIds: ['obs-traffic'] },
      ),
      claim(
        'c-duration',
        'The published disruption interval spans 79 hours 30 minutes.',
        'DERIVED',
        ['as15895'],
        ['ev-cloudflare'],
        't-disruption',
        'Elapsed time between the report’s endpoints; not downtime for every subscriber.',
        {
          premiseIds: ['c-traffic'],
          derivation: '2023-12-15T12:00Z minus 2023-12-12T04:30Z = 79.5 hours',
        },
      ),
      claim(
        'c-voice',
        'Mobile voice restoration began at 18:00 Kyiv time on 13 December.',
        'REPORTED',
        ['kyivstar'],
        ['ev-voice'],
        't-voice',
        'A restoration start, not completion. December Kyiv time is UTC+02:00.',
      ),
      claim(
        'c-mobile',
        'VEON reports mobile Internet restored across Ukraine on 15 December.',
        'REPORTED',
        ['kyivstar', 'ukraine'],
        ['ev-mobile'],
        't-mobile',
        'Customer experience could still vary; no precise restoration time supplied.',
      ),
      claim(
        'c-recovery',
        'VEON reports 99% of base stations operational in Ukrainian-government-controlled territory.',
        'REPORTED',
        ['kyivstar', 'ukraine'],
        ['ev-recovery'],
        't-recovery',
        '19 December statement. Not 99% of customers or land area; quality work continued.',
      ),
      claim(
        'c-data',
        'Kyivstar states subscriber personal data was not compromised.',
        'REPORTED',
        ['kyivstar'],
        ['ev-kyivstar'],
        't-recovery',
        'An operator statement, not independently verified forensic evidence.',
      ),
      claim(
        'c-link',
        'The measured traffic disruption is consistent with the operator’s reported service interruption.',
        'INFERRED',
        ['kyivstar', 'as15895'],
        ['ev-cloudflare', 'ev-kyivstar'],
        't-disruption',
        'Temporal agreement supports consistency, not independent proof of cause or attribution.',
        { premiseIds: ['c-attack', 'c-traffic'] },
      ),
      claim(
        'c-network',
        'The historical Cloudflare report identifies Kyivstar through AS15895.',
        'REPORTED',
        ['kyivstar', 'as15895'],
        ['ev-cloudflare'],
        't-disruption',
        'One network identifier; this is not a complete inventory of the operator’s infrastructure.',
      ),
      claim(
        'c-geography',
        'The outline provides country-level reference context.',
        'DERIVED',
        ['ukraine'],
        ['ev-geography'],
        't-reference',
        'Natural Earth reference cartography. Not outage extent or December 2023 control lines.',
        { derivation: 'Select Natural Earth v5.1.2 feature ADM0_A3=UKR.' },
      ),
      claim(
        'c-unknown',
        'Initial access, affected facilities and independently verified exfiltration remain unresolved in this bundle.',
        'UNKNOWN',
        ['kyivstar'],
        [],
        't-recovery',
        'Missing evidence is not evidence of absence.',
      ),
    ],
    relationships: [
      {
        id: 'r-target',
        from: 'event-attack',
        to: 'kyivstar',
        predicate: 'affected operator',
        status: 'REPORTED',
        claimIds: ['c-attack'],
        timeId: 't-attack',
      },
      {
        id: 'r-network',
        from: 'kyivstar',
        to: 'as15895',
        predicate: 'identified network',
        status: 'REPORTED',
        claimIds: ['c-network'],
        timeId: 't-disruption',
      },
      {
        id: 'r-observation',
        from: 'as15895',
        to: 'obs-traffic',
        predicate: 'measured disruption',
        status: 'OBSERVED',
        claimIds: ['c-traffic'],
        timeId: 't-disruption',
      },
      {
        id: 'r-country',
        from: 'kyivstar',
        to: 'ukraine',
        predicate: 'reported service geography',
        status: 'REPORTED',
        claimIds: ['c-mobile'],
        timeId: 't-mobile',
      },
      {
        id: 'r-geometry',
        from: 'ukraine',
        to: 'geo-ukraine',
        predicate: 'reference outline',
        status: 'DERIVED',
        claimIds: ['c-geography'],
        timeId: 't-reference',
      },
    ],
    events: [
      {
        id: 'event-attack',
        title: 'Service interruption',
        label: '12 DEC',
        timeId: 't-attack',
        entityIds: ['kyivstar', 'as15895', 'ukraine'],
        claimIds: ['c-attack', 'c-traffic', 'c-duration'],
        summary:
          'An operator-reported cyberattack. A separately measured Internet disruption.',
      },
      {
        id: 'event-voice',
        title: 'Voice recovery begins',
        label: '13 DEC',
        timeId: 't-voice',
        entityIds: ['kyivstar'],
        claimIds: ['c-voice'],
        summary:
          'Voice service starts returning. Recovery is gradual and setbacks remain possible.',
      },
      {
        id: 'event-mobile',
        title: 'Mobile Internet returns',
        label: '15 DEC',
        timeId: 't-mobile',
        entityIds: ['kyivstar', 'ukraine'],
        claimIds: ['c-mobile', 'c-traffic'],
        summary:
          'Reported mobile Internet recovery aligns with the end of the measured disruption interval.',
      },
      {
        id: 'event-recovery',
        title: 'Recovery expands',
        label: '19 DEC',
        timeId: 't-recovery',
        entityIds: ['kyivstar', 'ukraine'],
        claimIds: ['c-recovery', 'c-data'],
        summary:
          'Service categories are available again; quality and accessibility work continues.',
      },
    ],
    questions: [
      'Can IODA independently corroborate the AS-level disruption?',
      'Which facilities and dependencies were affected in December 2023?',
      'What primary forensic evidence establishes initial access or data exposure?',
    ],
  };
}
